# Generated by Django 3.2.6 on 2022-02-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_customer_employee_location_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfeedback',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='pharmacist_id',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='Dispense',
        ),
        migrations.DeleteModel(
            name='PatientFeedback',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
