# Generated by Django 3.2.6 on 2022-05-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
