# Generated by Django 3.2.6 on 2022-05-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_adminhod_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='PASSWORD',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='USERNAME',
        ),
    ]
